# Generated by Django 5.2.8 on 2026-07-03 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('user_name', models.CharField(max_length=255)),
                ('action_ru', models.TextField()),
                ('action_uz', models.TextField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('template_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('trigger_ru', models.CharField(max_length=255)),
                ('trigger_uz', models.CharField(max_length=255)),
                ('content_ru', models.TextField()),
                ('content_uz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('citizen_name', models.CharField(max_length=255)),
                ('citizen_phone', models.CharField(max_length=50)),
                ('title_ru', models.TextField()),
                ('title_uz', models.TextField()),
                ('registered_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('is_accepted', models.BooleanField(default=True)),
                ('extension_count', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=3)),
                ('material_type', models.CharField(default='ariza', max_length=50)),
                ('source_from', models.CharField(default='tashrif', max_length=50)),
                ('citizen_notification_text', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='AppealStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='api.material')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('rank_ru', models.CharField(max_length=100)),
                ('rank_uz', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=100)),
                ('photo', models.CharField(blank=True, max_length=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='api.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='api.officer'),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('case_num', models.CharField(blank=True, max_length=100, null=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.material')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.officer')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveVisit',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('citizen_name', models.CharField(max_length=255)),
                ('citizen_phone', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('purpose_ru', models.TextField()),
                ('purpose_uz', models.TextField()),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.officer')),
            ],
        ),
    ]
