# Generated by Django 4.2.30 on 2026-07-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(choices=[('registrator', 'Регистратор'), ('investigator', 'Следователь'), ('chief', 'Начальник')], max_length=50),
        ),
    ]
