# Generated by Django 4.2.30 on 2026-07-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
