# Generated by Django 4.2.30 on 2026-07-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatmessage_recipient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
