# Generated by Django 5.2.8 on 2026-07-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_officer_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_name', models.CharField(max_length=255)),
                ('is_like', models.BooleanField()),
                ('reason_ru', models.CharField(blank=True, max_length=255)),
                ('reason_uz', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.officer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
