# Generated by Django 5.2.8 on 2026-07-05 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 5, 19, 16, 28, 514659, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='status',
            field=models.CharField(choices=[('на_модерации', 'На модерации'), ('в_процессе', 'В процессе'), ('одобрено', 'Одобрено'), ('отказан', 'Отказан')], default='на_модерации', max_length=20),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='content_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='trigger_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='trigger_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
