# Generated by Django 5.2.8 on 2026-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_smstemplate_options_smstemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='iib',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='preliminary_article',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
