# Generated by Django 5.2.8 on 2026-07-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_material_iib_material_preliminary_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='extra_ids',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
