# Generated by Django 5.2.8 on 2026-08-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_material_mahalla'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='material_docs/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.material')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
