# Generated by Django 5.2.8 on 2026-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_materialdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
