# Generated by Django 4.2.30 on 2026-08-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_officer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taqiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mashina', 'Автомашина'), ('mol_mulk', 'Имущество'), ('uy_joy', 'Жилое помещение')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('response_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('amalda', 'Действует'), ('bekor_qilingan', 'Снят')], default='amalda', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taqiqlar', to='api.material')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taqiqlar', to='api.officer')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Ekspertiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sud_tibbiy', 'Судебно-медицинская'), ('sud_biologik', 'Судебно-биологическая'), ('sud_xatshunoslik', 'Судебно-почерковедческая'), ('sud_texnik', 'Судебно-техническая'), ('sud_dnk', 'Судебная ДНК')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('response_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('tayinlangan', 'Назначена'), ('jarayonda', 'В процессе'), ('yakunlangan', 'Завершена')], default='tayinlangan', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ekspertizas', to='api.material')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ekspertizas', to='api.officer')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gai', 'ГАИ (БДДА)'), ('notarius', 'Нотариус'), ('kadastr', 'Кадастр'), ('soliq', 'Налоговая')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('response_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('yuborilgan', 'Отправлен'), ('javob_kelgan', 'Ответ получен'), ('rad_etilgan', 'Отклонён')], default='yuborilgan', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.material')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='api.officer')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
